version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab
    restart: always
    hostname: '${HOST_NAME}'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${HOST_NAME}'
    ports:
      - '${MAP_INTERFACE}${MAP_PORT_WEB}:80'
      - '${MAP_INTERFACE}${MAP_PORT_WEBS}:443'
      - '${MAP_INTERFACE}${MAP_PORT_SSH}:22'
    volumes:
      - '${BIND_DIR}/config:/etc/gitlab'
      - '${BIND_DIR}/logs:/var/log/gitlab'
      - '${BIND_DIR}/data:/var/opt/gitlab'
    shm_size: '256m'
