version: "3"

networks:
  external:

services:
  server:
    image: docker.gitea.com/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - external
    volumes:
      - ${BIND_DIR}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${MAP_INTERFACE}${MAP_PORT_WEB}:3000"
      - "${MAP_INTERFACE}${MAP_PORT_SSH}:22"
