# Mediawiki with ENV file credentials
version: '3'
services:
  mediawiki:
    image: mediawiki
    restart: always
    ports:
      - 8080:80
    links:
      - database
    volumes:
      - images:/var/www/html/images
      
      # Load extensions individually to avoid exporting the default ones
      - DeleteBatch:/var/www/html/images/extensions/DeleteBatch
      - PageInCat:/var/www/html/images/extensions/PageInCat
      - ParserFunctions:/var/www/html/images/extensions/ParserFunctions
      - Purge:/var/www/html/images/extensions/Purge
      - UploadWizard:/var/www/html/images/extensions/UploadWizard
      - Variables:/var/www/html/images/extensions/Variables

      # Set site favicon
      - favicon.ico:/var/www/html/favicon.ico

      # After initial setup, download LocalSettings.php to the same directory as
      # this yaml and uncomment the following line and use compose to restart
      # the mediawiki service
      # - ./LocalSettings.php:/var/www/html/LocalSettings.php
  # This key also defines the name of the database host used during setup instead of the default "localhost"
  database:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - credentials.env

volumes:
  images:
  db:
