# Mediawiki with ENV file credentials
version: '3'
services:
  mediawiki-tt-test:
    #    user: "1001:1001"
    image: mediawiki
    restart: always
    ports:
      - 8080:80
    links:
      - database
    volumes:
      # Wiki images
      - /home/docker/services/tt-wiki-test/images:/var/www/html/images
      
      # Load extensions individually to avoid exporting the default ones
      #- /home/docker/services/tt-wiki-test/extensions:/var/www/html/extensions
      
      # Load extensions individually to avoid exporting the default ones
      - /home/docker/services/tt-wiki-test/extensions/DeleteBatch:/var/www/html/extensions/DeleteBatch
      - /home/docker/services/tt-wiki-test/extensions/PageInCat:/var/www/html/extensions/PageInCat
      - /home/docker/services/tt-wiki-test/extensions/ParserFunctions:/var/www/html/extensions/ParserFunctions
      - /home/docker/services/tt-wiki-test/extensions/Purge:/var/www/html/extensions/Purge
      - /home/docker/services/tt-wiki-test/extensions/UploadWizard:/var/www/html/extensions/UploadWizard
      - /home/docker/services/tt-wiki-test/extensions/Variables:/var/www/html/extensions/Variables

      # Set site favicon
      - /home/docker/services/tt-wiki-test/favicon.ico:/var/www/html/favicon.ico

      # Import existing LocalSettings
      - /home/docker/services/tt-wiki-test/LocalSettings.php:/var/www/html/LocalSettings.php
  # This key also defines the name of the database host used during setup instead of the default "localhost"
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD}

volumes:
  images:
