# Mediawiki with ENV file credentials
version: '3'
services:
  mediawiki:
    container_name: semanticmediawiki
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${MAP_INTERFACE}${MAP_PORT}:80"
    depends_on:
      - database
    networks:
      - external
      - internal
    volumes:
      # Wiki images
      - ${BIND_DIR}/images:/var/www/html/images
      
      # Load whole extensions folder (MUST exporti default extensions)
      #- ${BIND_DIR}/extensions:/var/www/html/extensions
      
      # Use custom extensions directory
      - ${BIND_DIR}/extensions:/var/www/html/extensions-custom

      # Set site favicon
      - ${BIND_DIR}/favicon.ico:/var/www/html/favicon.ico

      # Import LocalSettings
      # After initialization unset ${INIT}
      - ${BIND_DIR}/LocalSettings.php:${INIT}/var/www/html/LocalSettings.php
      
  database:
    image: mariadb
    restart: always
    networks:
      - internal
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - ${BIND_DIR}/db:/var/lib/mysql

volumes:
  images:  
  db:
  
networks:
  external:
  internal:
    internal: true                                                    
