version: "2.1"
services:
  mastodon:
    image: lscr.io/linuxserver/mastodon:latest
    container_name: mastodon
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - LOCAL_DOMAIN=${LOCAL_DOMAIN}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_NAME=mastodon
      - DB_PASS=${DB_PASS}
      - DB_PORT=5432
      - ES_ENABLED=true
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - OTP_SECRET=${OTP_SECRET}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_LOGIN=${SMTP_LOGIN}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM_ADDRESS=${SMTP_FROM_ADDRESS}
      - S3_ENABLED=false
      - WEB_DOMAIN=${LOCAL_DOMAIN}
      - ES_HOST=es
      - ES_PORT=9200
      - ES_USER=elastic
      - ES_PASS=${ES_PASS} # Set at runtime
    volumes:
      - ${MASTODON_BIND}/config:/config
    ports:
      - ${MAP_INTERFACE}${MAP_PORT_WEB}:443
    restart: unless-stopped
    depends_on:
      - es
      - db
      - redis
    networks:
      - external
      - internal

  db:
    restart: always
    image: postgres:14-alpine
    shm_size: 256mb
    networks:
      - internal
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: mastodon
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - ${MASTODON_BIND}/postgres14:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:7-alpine
    networks:
      - internal
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - ${MASTODON_BIND}/redis:/data

  es:
    restart: always
    image: nextcloud/aio-fulltextsearch
    networks:
      - internal
    volumes:
      - ${MASTODON_BIND}/esdata:/usr/share/elasticsearch/data
    environment:
      TZ: ${TZ}
      ELASTIC_PASSWORD: ${ES_PASS}
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms1024M -Xmx1024M
      PATH: /usr/share/elasticsearch/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      ELASTIC_CONTAINER: true
      xpack.security.enabled: false


networks:
  external:
  internal:
    internal: true
