services:
  nextcloud:
    # Due to accidentally version locking, sequential updates must be done to allow the cumulative changes to happen. 
    #image: nextcloud/all-in-one:20230626_101439-latest # Starting point
    #image: nextcloud/all-in-one:20230720_134150-latest # Test of going one update farther
    image: nextcloud/all-in-one:20230817_065941-latest
    #image: nextcloud/all-in-one:20230912_084059-latest
    #image: nextcloud/all-in-one:20230916_091439-latest
    #image: nextcloud/all-in-one:20231027_071516-latest
    #image: nextcloud/all-in-one:20231113_125854-latest
    #image: nextcloud/all-in-one:20231212_115941-latest
    #image: nextcloud/all-in-one:20240109_092105-latest
    #image: nextcloud/all-in-one:20240201_120631-latest
    #image: nextcloud/all-in-one:latest # The Goal
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      # This line is not allowed to be changed as otherwise the built-in backup solution will not work
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - ${SETUP_PORT}:8080
      - 8443:8443
      - 81:80
    networks:
      - external
    environment:
      #      - WATCHTOWER_DOCKER_SOCKET_PATH=$XDG_RUNTIME_DIR/docker.sock
      # Is needed when running behind a web server or reverse proxy (like
      # Apache, Nginx, Cloudflare Tunnel and else).
      # See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - APACHE_PORT=${MAP_PORT}
      - APACHE_IP_BINDING=${MAP_INTERFACE}
      # Allows to set the host directory for Nextcloud's datadir.
      # Warning: do not set or adjust this value after the initial Nextcloud
      # installation is done!
      # See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
      - NEXTCLOUD_DATADIR=${USER_DATA_FOLDER}
      # Allows the Nextcloud container to access the chosen directory on the
      # host.
      # See https://github.com/nextcloud/all-in-one#how-to-allow-the-nextcloud-container-to-access-directories-on-the-host
      - NEXTCLOUD_MOUNT=/mnt/
      - NEXTCLOUD_UPLOAD_LIMIT=0G # Disable public upload
      # - NEXTCLOUD_MAX_TIME=3600
      - NEXTCLOUD_MEMORY_LIMIT=${NEXTCLOUD_MEMORY_LIMIT}
      # - TALK_PORT=3478

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed as otherwise the built-in backup solution will not work

networks:
  external:
