version: "2.1"
services:
  db:
    restart: always
    image: postgres:13
    shm_size: 256mb
    ports:
      - ${MAP_INTERFACE}${MAP_PORT_}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - ${MOUNT_BIND}/postgres13:/var/lib/postgresql/data
