version: "2.1"
services:
  db:
    restart: always
    image: postgres:9.5.21-alpine
    shm_size: 256mb
    ports:
      - ${MAP_INTERFACE}${MAP_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ${MOUNT_BIND}/postgres:/var/lib/postgresql/data
    dns:
      - 8.8.8.8
      - 4.4.4.4
      - 1.1.1.1
